CREATE TABLE raw.service_requests (
    unique_key TEXT,
    created_date TEXT,
    closed_date TEXT,
    agency TEXT,
    agency_name TEXT,
    complaint_type TEXT,
    descriptor TEXT,
    location_type TEXT,
    incident_zip TEXT,
    city TEXT,
    borough TEXT,
    status TEXT,
    due_date TEXT,
    resolution_description TEXT,
    resolution_action_updated_date TEXT,
    open_data_channel_type TEXT,
    latitude TEXT,
    longitude TEXT,
    ingestion_run_id UUID,
    ingested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);