CREATE TABLE IF NOT EXISTS raw.service_requests (
    unique_key TEXT,
    created_date TEXT,
    closed_date TEXT,
    agency TEXT,
    agency_name TEXT,
    complaint_type TEXT,
    descriptor TEXT,
    location_type TEXT,
    incident_zip TEXT,
    city TEXT,
    borough TEXT,
    status TEXT,
    due_date TEXT,
    resolution_description TEXT,
    resolution_action_updated_date TEXT,
    open_data_channel_type TEXT,
    latitude TEXT,
    longitude TEXT,
    run_id UUID NOT NULL,
    ingested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS analytics.tickets (
    ticket_id BIGINT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    closed_at TIMESTAMP,
    due_at TIMESTAMP,
    agency_code VARCHAR(50),
    agency_name TEXT,
    complaint_type TEXT,
    descriptor TEXT,
    location_type TEXT,
    incident_zip VARCHAR(20),
    city TEXT,
    borough TEXT,
    source_status TEXT,
    normalized_status VARCHAR(30),
    submission_channel TEXT,
    resolution_description TEXT,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    resolution_hours NUMERIC(12,2),
    open_age_hours NUMERIC(12,2),
    aging_bucket VARCHAR(30),
    sla_status VARCHAR(30),
    is_open BOOLEAN,
    is_closed BOOLEAN,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    resolution_updated_at TIMESTAMP,
    source_run_id UUID,
    snapshot_at TIMESTAMP,
);

CREATE TABLE IF NOT EXISTS audit.pipeline_runs (
    run_id UUID PRIMARY KEY,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    status VARCHAR(20) NOT NULL,
    date_from DATE NOT NULL,
    date_to DATE NOT NULL,
    rows_extracted INTEGER NOT NULL DEFAULT 0,
    rows_loaded INTEGER NOT NULL DEFAULT 0,
    quality_summary JSONB,
    raw_file_path TEXT,
    error_message TEXT,
    CONSTRAINT chk_pipeline_status
        CHECK (status IN ('RUNNING', 'SUCCESS', 'FAILED'))
);